---
config:
  layout: elk
---

flowchart TD

    AluminumProducts

    Oscillators

    Nitrogen

    AluminumProducts -- 350xAlu. Casing --> Frames
    Computing -- 8xRCU --> Frames
    Nitrogen -- 175xNitrogen --> Frames
    Frames

    OilBasedProducts -- 250xPlastic --> Electronics
    Motors -- 8xStator --> Electronics
    Electronics

    OilBasedProducts -- 72xRubber --> Motors
    Cooling -- 12xCooling --> Motors
    Computing -- 6xRCU --> Motors
    Motors["*tors"]

    AluminumProducts -- 305xAlu. Sheet --> Cooling
    OilBasedProducts -- 60xRubber --> Cooling
    Nitrogen -- 750xNitrogen --> Cooling
    Cooling

    OilBasedProducts -- 95xPlastic --> Computing
    Oscillators -- 34xOscillator --> Computing
    AluminumProducts -- 384xAlu. Casing --> Computing
    Cooling -- 10xCooling--> Computing
    Computing

    OilBasedProducts -- 185xRubber --> ProjectAssembly4
    Motors -- 50xStator / 15xRotor/ 15xMotor/ 3xTurbo --> ProjectAssembly4
    Frames -- 7xModular / 10xHeavy / 3xFused / 1xPressure --> ProjectAssembly4
    Electronics -- 50xCircuit / 13xHSC / 5xRod --> ProjectAssembly4
    Cooling -- 9xCooling--> ProjectAssembly4
    Computing -- 20xComputer / 5xSuper --> ProjectAssembly4
    ProjectAssembly4["Project Assembly Parts #4"]

    AluminumProducts -- 27xAlu. Sheet --> ProjectAssembly5
    Oscillators -- 3xOscillator --> ProjectAssembly5
    Computing -- 2xSuper --> ProjectAssembly5
    ProjectAssembly4 o-. 4xPasta / 2xMagnetic / 1xThermal / 1xADS .-o ProjectAssembly5
    ProjectAssembly5["Project Assembly Parts #5"]