---
config:
  layout: elk
---

flowchart TD

    AluminumProducts

    Oscillators

    Nitrogen

    AluminumProducts -- 300xAlu. Casing --> Frames
    Computing -- 2xRCU --> Frames
    Nitrogen -- 100xNitrogen --> Frames
    Frames

    OilBasedProducts -- 250xPlastic --> Electronics
    Motors -- 8xStator --> Electronics
    Electronics

    OilBasedProducts -- 72xRubber --> Motors
    Cooling -- 12xCooling --> Motors
    Computing -- 6xRCU --> Motors
    Motors["*tors"]

    AluminumProducts -- 225xAlu. Sheet --> Cooling
    OilBasedProducts -- 44xRubber --> Cooling
    Nitrogen -- 550xNitrogen --> Cooling
    Cooling

    OilBasedProducts -- 150xPlastic --> Computing
    Oscillators -- 28xOscillator --> Computing
    AluminumProducts -- 192xAlu. Casing --> Computing
    Cooling -- 10xCooling--> Computing
    Computing

    OilBasedProducts -- 185xRubber --> ProjectAssembly
    Motors -- 50xStator / 15xRotor/ 15xMotor/ 3xTurbo --> ProjectAssembly
    Frames -- 7xModular / 10xHeavy / 3xFused / 1xPressure --> ProjectAssembly
    Electronics -- 50xCircuit / 13xHSC / 5xRod --> ProjectAssembly
    Cooling -- 9xCooling--> ProjectAssembly
    Computing -- 20xComputer / 5xSuper --> ProjectAssembly
    ProjectAssembly["Project Assembly Parts"]